### ISSUE TITLE
TypeError: force.sourceConvertApi is not a constructor

### ISSUE THREAD

**Issue by havok** [heroku/salesforce-buildpack#18]
I'm currently using this buildpack to deploy my lightning app to a given environment. I'm currently running into an issue in the deploy call.
Here's the stack trace: with debug info 

`
 [DEBUG] Deploy options: {"polltimeout":600000,"pollinterval":10000,"deploydir":".cache/mdapi-source","targetusername":"_sfdc_buildpack_workspace@salesforce.com","wait":600000,"verbose":true,"json":true,"loglevel":"debug"}
 !     TypeError: force.sourceConvertApi is not a constructor
    at deploySource (/app/.salesforce/force.js:201:30)
    at release (/app/.salesforce/force.js:262:27)
    at Promise.resolve.then (/app/.salesforce/force.js:325:28)
    at tryCatcher (/app/.local/heroku/plugins/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/.local/heroku/plugins/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/app/.local/heroku/plugins/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/app/.local/heroku/plugins/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/app/.local/heroku/plugins/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/app/.local/heroku/plugins/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/app/.local/heroku/plugins/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
`

Any help would be much appreciated.

**Comment by wadewegner** [comment]
We are in the process of revising this pipeline. I'm going to close this issue as we've gone a different path. Thanks!
